import { COLORS } from './colors';

/**
 * A small, semi-transparent watermark for exportable charts and panels.
 * Appears in the lower right corner when rendered.
 */
export function Watermark() {
  return (
    <div
      style={{
        position: 'absolute',
        right: 12,
        bottom: 2,
        opacity: 0.45,
        fontSize: '0.95rem',
        color: COLORS.primary,
        fontWeight: 600,
        pointerEvents: 'none',
        zIndex: 1000,
        userSelect: 'none',
      }}
      aria-hidden="true"
    >
      Generated by SCUM DB Web Analyser
    </div>
  );
}
